local module = ... or D:module('hybrid_perk_deck')
local UpgradesTweakData = module:hook_class("UpgradesTweakData")

module:post_hook(UpgradesTweakData, "_player_definitions", function(self)
	self.values.player.__pd2_muscle_more_hp = 1.5 -- HP multiplier (originally 1; 1.8 with previous mods)
	self.values.player.__pd2_muscle_regen_hp = 0.006 -- HP regeneration per interval (originally 0; 0.03 with previous mods)
	self.values.player.__pd2_muscle_regen_hp_dt = 1 -- HP regeneration interval in seconds (originally 0; 5 with previous mods)
	self.values.player.__pd2_muscle_panic_suppression_rate = 0.001 -- Panic suppression probability (originally 0; 0.35 with previous mods)
	self.values.player.__pd2_muscle_panic_suppression_dis = 500 -- Panic suppression distance (originally 0; 1500 with previous mods)
    self.values.player.rogue_dodge_chance = 0.15 -- Dodge probability (originally 0; 0.6 with previous mods)
	self.values.player.rogue_fast_hand = 3.0 -- Swap speed multiplier (originally 1; 1.8 with previous mods)
	self.values.player.armorer_deck_addon_armor = 0.1 -- Additional armor proportion (originally 0; 0.35 with previous mods)
	self.values.player.armorer_deck_inmune_during = 2 -- Armor immunity duration (originally 0; 2 with previous mods)
	self.values.player.armorer_deck_inmune_cooldown = 0 -- Armor immunity cooldown (originally 0; 15 with previous mods)
end, true)