local module = ... or D:module('hybrid_perk_deck')
local UpgradesTweakData = module:hook_class("UpgradesTweakData")

module:post_hook(UpgradesTweakData, "_player_definitions", function(self)
	self.values.player.__pd2_muscle_more_hp = 1.5 -- HP multiplier (originally 1; 1.8 with previous mods)
	self.values.player.__pd2_muscle_regen_hp = 0.006 -- HP regeneration per interval (originally 0; 0.03 with previous mods)
	self.values.player.__pd2_muscle_regen_hp_dt = 1 -- HP regeneration interval in seconds (originally 0; 5 with previous mods)
	self.values.player.__pd2_muscle_panic_suppression_rate = 0.002 -- Panic suppression probability (originally 0; 0.35 with previous mods)
	self.values.player.__pd2_muscle_panic_suppression_dis = 750 -- Panic suppression distance (originally 0; 1500 with previous mods)
    self.values.player.rogue_dodge_chance = 0.15 -- Dodge probability (originally 0; 0.6 with previous mods)
	self.values.player.rogue_fast_hand = 3.0 -- Swap speed multiplier (originally 1; 1.8 with previous mods)
	self.values.player.toolset[1] = 0.825 -- Remaining proportion of interaction time when using a Level 1 Toolkit (originally 0.95)
	self.values.player.toolset[2] = 0.75 -- Remaining proportion of interaction time when using a Level 2 Toolkit (originally 0.9)
	self.values.player.toolset[3] = 0.625 -- Remaining proportion of interaction time when using a Level 3 Toolkit (originally 0.85)
	self.values.player.toolset[4] = 0.5 -- Remaining proportion of interaction time when using a Level 4 Toolkit (originally 0.8)
	self.values.extra_cable_tie.quantity[1] = 2 -- Extra cable ties added by the Level 1 Extra Cable Ties equipment (originally 1)
    self.values.extra_cable_tie.quantity[2] = 4 -- Extra cable ties added by the Level 2 Extra Cable Ties equipment (originally 2)
    self.values.extra_cable_tie.quantity[3] = 6 -- Extra cable ties added by the Level 3 Extra Cable Ties equipment (originally 3)
    self.values.extra_cable_tie.quantity[4] = 8 -- Extra cable ties added by the Level 4 Extra Cable Ties equipment (originally 4)
end, true)
